### ISSUE TITLE
KeyError: 'core_job_map'

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#231]
```
$ PYTHONPATH=`pwd` ./source/qtop.py
Traceback (most recent call last):
  File "./source/qtop.py", line 2159, in <module>
    cluster = Cluster(document, worker_nodes, WNFilter, config, options)
  File "./source/qtop.py", line 1682, in __init__
    self.analyse()
  File "./source/qtop.py", line 1717, in analyse
    self._calculate_jobs_per_node(self.workernode_dict)
  File "./source/qtop.py", line 1910, in _calculate_jobs_per_node
    node_job_set = set(workernode_dict[node]['core_job_map'].values())
KeyError: 'core_job_map'
```

introduced via:
https://github.com/qtop/qtop/pull/211/files#diff-0ef67520eb904b36e99cf6339e35b315R1873

**Comment by fgeorgatos** [comment]
fixed via #253
