### ISSUE TITLE
Prevent under OAR KeyError: '4022285' or KeyError: '1542861'

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#249]

**Comment by sfranky** [comment]
could you be a little less specific? ;)

**Comment by fgeorgatos** [comment]
one stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/gaiagpfs/users/homedirs/fgeorgatos/qtop/qtop.py", line 2175, in <module>
    worker_nodes = ensure_worker_nodes_have_qnames(worker_nodes, jobs_dict)  # TODO is this bad to have beforehand?
  File "/mnt/gaiagpfs/users/homedirs/fgeorgatos/qtop/qtop.py", line 701, in ensure_worker_nodes_have_qnames
    my_queues = set(jobs_dict[re.sub(r'\[\d+\]', r'[]', job_id)].job_queue for job_id in my_jobs)  # also takes care of job arrays
  File "/mnt/gaiagpfs/users/homedirs/fgeorgatos/qtop/qtop.py", line 701, in <genexpr>
    my_queues = set(jobs_dict[re.sub(r'\[\d+\]', r'[]', job_id)].job_queue for job_id in my_jobs)  # also takes care of job arrays
KeyError: '4031720'
```

one more, one more!

**Comment by fgeorgatos** [comment]
while you are at it, check why R+Q are 0,0

**Comment by sfranky** [comment]
@fgeorgatos this is a classic: this job exists in oarnodes_s_Y but not in oarstat, and the strict check takes place too later for that..
