### ISSUE TITLE
stacktrace while collecting anonymized sample (which worked otherwise)

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#280]
```
Log file created in /home/fg/.local/qtop/logs/qtop.log
Sample files saved in /tmp/qtop_results_fg/qtop_sample_fgeorgatos.tar
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/fgeorgatos/qtop/qtop.py", line 2456, in <module>
    fileutils.add_to_sample([QTOP_LOGFILE], savepath, SAMPLE_FILENAME)
  File "qtop_py/fileutils.py", line 78, in add_to_sample
  File "/usr/lib64/python2.6/tarfile.py", line 1687, in open
    return cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python2.6/tarfile.py", line 1697, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python2.6/tarfile.py", line 1577, in __init__
    if self.next() is None:
  File "/usr/lib64/python2.6/tarfile.py", line 2328, in next
    raise ReadError(str(e))
tarfile.ReadError: empty header
```

**Comment by fgeorgatos** [comment]
fixed via #281
