### ISSUE TITLE
KeyError: 'rem_empty_corelines' ; this should not have happened

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#290]
```
Traceback (most recent call last):
  File "/home/fgeorgatos/qtop/qtop.py", line 2350, in <module>

  File "/home/fgeorgatos/qtop/qtop.py", line 751, in update_config_with_cmdline_vars
    Number of Extra tables needed is calculated inside the calc_all_wnid_label_lines fu
KeyError: 'rem_empty_corelines'
```

**Comment by fgeorgatos** [comment]
investigate and either fix or close - is this error reproducible?
