### ISSUE TITLE
easy feature request:

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#291]
instead of failing, this could have actually done something useful, by striping away the filename, ie. `dirname`

```
$ module load sge;./qtop/qtop.py -FGrr -s myqtoptest/qstat.F.xml.stdout
Traceback (most recent call last):
  File "./qtop/qtop.py", line 2358, in <module>
    options = init_dirs(options, savepath)
  File "./qtop/qtop.py", line 780, in init_dirs
    os.chdir(options.workdir)
OSError: [Errno 20] Not a directory: '/home/robinhood/myqtoptest/qstat.F.xml.stdout'
```

**Comment by nikkkkj** [comment]
I am working on a small, focused fix for this: when `-s/--SetSourceDir` points at an existing scheduler output file, normalize it to the parent directory before `init_dirs()` calls `chdir`. I will keep the patch scoped and include a regression test.

**Comment by RahulGonela** [comment]
Hi! I noticed there were some recent attempts to address this issue. Is this issue still available for contribution, or has the fix already been incorporated elsewhere? I'd be happy to work on it if it's still open.


> I am working on a small, focused fix for this: when `-s/--SetSourceDir` points at an existing scheduler output file, normalize it to the parent directory before `init_dirs()` calls `chdir`. I will keep the patch scoped and include a regression test.

**Comment by by-Kaimercer** [comment]
Hi! I'd like to claim this one. The fix should be a small change in qtop_py/qtop.py's init_dirs() to os.path.dirname() the path when it's a file rather than a directory, so os.chdir works.

I'll work against the develop branch, follow CONTRIBUTING.md (DCO sign-off + dated (human): PR title), and add a regression test under tests/test_qtop.py.

PR incoming shortly.
