### ISSUE TITLE
if job name has a colon in it I get a traceback

### ISSUE THREAD

**Issue by stetner** [qtop/qtop#292]
```
$ qsub -N aa:bb -I
....

$ git status
git: /opt/pkg/2015Q2/lib/libz.so.1: no version information available (required by git)
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

$ ./qtop
Traceback (most recent call last):
  File "/opt/Modules/Python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/Modules/Python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/shares/common/users/d.stetner/build/qtop/qtop.py", line 2376, in <module>
    job_ids, user_names, job_states, job_queues = scheduling_system.get_jobs_info()
  File "qtop_py/plugins/pbs.py", line 186, in get_jobs_info
  File "qtop_py/plugins/pbs.py", line 61, in extract_qstat
  File "qtop_py/serialiser.py", line 27, in _process_qstat_line
AttributeError: 'NoneType' object has no attribute 'group'

Change to develop

$ git status
git: /opt/pkg/2015Q2/lib/libz.so.1: no version information available (required by git)
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean

$ ./qtop --version
qtop current version: 0.9.20161222

$ ./qtop
Traceback (most recent call last):
  File "/opt/Modules/Python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/Modules/Python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/shares/common/users/d.stetner/build/qtop/qtop.py", line 2376, in <module>
    job_ids, user_names, job_states, job_queues = scheduling_system.get_jobs_info()
  File "qtop_py/plugins/pbs.py", line 186, in get_jobs_info
  File "qtop_py/plugins/pbs.py", line 61, in extract_qstat
  File "qtop_py/serialiser.py", line 27, in _process_qstat_line
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by stetner** [comment]
Fix is to add a colon to characters in line 16 of qtop_py/plugins/pbs.py

                             r'(?P<name>[\w%:.=+/{}-]+)\s+' \

**Comment by sfranky** [comment]
Thanks! this will be pushed soon. 
Also, a more informative message will be shown instead, next time qtop cannot parse qstat  because of an unknown character.

**Comment by sfranky** [comment]
fixed in develop! closing issue.

**Comment by fgeorgatos** [comment]
fixed in this location, let us know if further work is needed in there:
https://github.com/qtop/qtop/pull/294/files#diff-23f7a4821fcaf1bc84a5046d9669d11bL16
