### ISSUE TITLE
Why not bail out (or bork out!) with better error messages?!

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#36]
I overcharged a queue and things started looking fishy, it ended up crying in command prompt:
(fine with that, let's make it more clear what went wrong!)

```
[fg@hello qtop]$ qstat -F -xml>qstat.F.xml.stdout && ./qtop.py -s . -c
===> Worker Nodes occupancy <=== (you can read vertically the node IDs; nodes in free state are noted with - )
12345={__WNID__}
----d=Node state
_____=Core0
_____=Core1
_____=Core2
_____=Core3
_____=Core4
_____=Core5
_____=Core6
_____=Core7
_____=Core8
_____=Core9
_____=Core10
_____=Core11
_____=Core12
_____=Core13
_____=Core14
_____=Core15
_____=Core16
_____=Core17
_____=Core18
_____=Core19
_____=Core20
_____=Core21
_____=Core22
_____=Core23
_____=Core24
_____=Core25
_____=Core26
_____=Core27
_____=Core28
_____=Core29
_____=Core30
_____=Core31

===> User accounts and pool mappings <===   ('all' also includes those in C and W states, as reported by qstat)
id|    R +    Q /  all |    unix account | Grid certificate DN (info only available under elevated privileges)

Thanks for watching!

[fg@hello qtop]$ watch -d 'qstat -F -xml>qstat.F.xml.stdout && ./qtop.py -s . -c'
[fg@hello qtop]$ Traceback (most recent call last):
  File "./qtop.py", line 16, in <module>
    from pbs import *
  File "/home/fgeorgatos/arena/qtop/pbs.py", line 4, in <module>
    import yaml
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/site-packages/yaml/__init__.py", line 8, in <module>
    from loader import *
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/site-packages/yaml/loader.py", line 4, in <module>
    from reader import *
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/site-packages/yaml/reader.py", line 45, in <module>
    class Reader(object):
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/site-packages/yaml/reader.py", line 137, in Reader
    NON_PRINTABLE = re.compile(u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/re.py", line 240, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 504, in compile
    code = _code(p, flags)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 486, in _code
    _compile_info(code, p, flags)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 464, in _compile_info
    _compile_charset(charset, flags, code)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 183, in _compile_charset
    for op, av in _optimize_charset(charset, fixup):
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 226, in _optimize_charset
    return _optimize_unicode(charset, fixup)
  File "/home/fgeorgatos/.local/easybuild/software/Python/2.7.3-goolf-1.4.10/lib/python2.7/sre_compile.py", line 303, in _optimize_unicode
    import array
KeyboardInterrupt

[fg@hello qtop]$
```

**Comment by fgeorgatos** [comment]
I'm closing this, since it is not specific request and it has been handled for quite a while
