### ISSUE TITLE
Non-interactive runs break out with an error

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#95]
This occured while sending qtop to be executed on a grid machine

```
2015-12-17 01:24:14 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1572, in <module>
    with raw_mode(sys.stdin):
  File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "./qtop.py", line 42, in raw_mode
    old_attrs = termios.tcgetattr(file.fileno())
error: (25, 'Inappropriate ioctl for device')
```

**Comment by sfranky** [comment]
possible fix in fix-issue#95-ioctl

**Comment by sfranky** [comment]
to be tested in the Grid

**Comment by fgeorgatos** [comment]
possibly fixed and never seen since; closing case as irrelevant, at present - reopen if in doubt
